import {
  CAMPAIGN_INPUTS,
  CONTACT_INFO,
  DEBT_ART_PM_ASSET_INFO,
  DEBT_ART_PM_DOCUMENTS,
  DEBT_ART_PM_GENERAL_INFO,
  DEBT_ART_PM_INVESTMENT_INFO,
  DEBT_ART_PM_KPI,
  DEBT_ART_SM_ASSET_INFO,
  DEBT_ART_SM_DOCUMENTS,
  DEBT_ART_SM_GENERAL_INFO,
  DEBT_ART_SM_INVESTMENT_INFO,
  DEBT_INFRASTRUCTURE_PM_ASSET_INFO,
  DEBT_INFRASTRUCTURE_PM_DOCUMENTS,
  DEBT_INFRASTRUCTURE_PM_GENERAL_INFO,
  DEBT_INFRASTRUCTURE_PM_INVESTMENT_INFO,
  DEBT_INFRASTRUCTURE_PM_KPI,
  DEBT_INFRASTRUCTURE_SM_ASSET_INFO,
  DEBT_INFRASTRUCTURE_SM_DOCUMENTS,
  DEBT_INFRASTRUCTURE_SM_GENERAL_INFO,
  DEBT_INFRASTRUCTURE_SM_INVESTMENT_INFO,
  DEBT_INFRASTRUCTURE_SM_KPI,
  DEBT_PE_PM_BUSINESS_INFO,
  DEBT_PE_PM_DOCUMENTS,
  DEBT_PE_PM_INVESTMENT_INFO,
  DEBT_PE_PM_KPI,
  DEBT_PE_SM_BUSINESS_INFO,
  DEBT_PE_SM_DOCUMENTS,
  DEBT_PE_SM_INVESTMENT_INFO,
  DEBT_PE_SM_KPI,
  DEBT_RE_PM_ASSET_INFO,
  DEBT_RE_PM_DOCUMENTS,
  DEBT_RE_PM_GENERAL_INFO,
  DEBT_RE_PM_INVESTMENT_INFO,
  DEBT_RE_PM_KPI,
  DEBT_RE_PM_NONFINANCIAL_INFO,
  DEBT_RE_SM_ASSET_INFO,
  DEBT_RE_SM_DOCUMENTS,
  DEBT_RE_SM_GENERAL_INFO,
  DEBT_RE_SM_INVESTMENT_INFO,
  EQUITY_INFRASTRUCTURE_PM_ASSET_INFO,
  EQUITY_INFRASTRUCTURE_PM_DOCUMENTS,
  EQUITY_INFRASTRUCTURE_PM_GENERAL_INFO,
  EQUITY_INFRASTRUCTURE_PM_INVESTMENT_INFO,
  EQUITY_INFRASTRUCTURE_PM_KPI,
  EQUITY_INFRASTRUCTURE_SM_ASSET_INFO,
  EQUITY_INFRASTRUCTURE_SM_DOCUMENTS,
  EQUITY_INFRASTRUCTURE_SM_GENERAL_INFO,
  EQUITY_INFRASTRUCTURE_SM_INVESTMENT_INFO,
  EQUITY_INFRASTRUCTURE_SM_KPI,
  EQUITY_PE_PM_BUSINESS_INFO,
  EQUITY_PE_PM_DOCUMENTS,
  EQUITY_PE_PM_GENERAL_INFO,
  EQUITY_PE_PM_INVESTMENT_INFO,
  EQUITY_PE_PM_KPI,
  EQUITY_PE_SM_BUSINESS_INFO,
  EQUITY_PE_SM_DOCUMENTS,
  EQUITY_PE_SM_GENERAL_INFO,
  EQUITY_PE_SM_INVESTMENT_INFO,
  EQUITY_PE_SM_KPI_INFO,
  EQUITY_RE_PM_ASSET_INFO,
  EQUITY_RE_PM_DOCUMENTS,
  EQUITY_RE_PM_GENERAL_INFO,
  EQUITY_RE_PM_INVESTMENT_INFO,
  EQUITY_RE_PM_KPI_INFO,
  EQUITY_RE_PM_NONFINANCIAL_INFO,
  EQUITY_RE_SM_ASSET_INFO,
  EQUITY_RE_SM_DOCUMENTS,
  EQUITY_RE_SM_GENERAL_INFO,
  EQUITY_RE_SM_INVESTMENT_INFO,
  EQUITY_RE_SM_KPI_INFO,
  EQUITY_RE_SM_NONFINANCIAL_INFO,
  FUND_FUND_PM_DOCUMENTS,
  FUND_FUND_PM_GENERAL_INFO,
  FUND_FUND_PM_INVESTMENT_INFO,
  FUND_FUND_PM_KPI,
  FUND_FUND_PM_STRATEGY,
  FUND_FUND_SM_DOCUMENTS,
  FUND_FUND_SM_STRATEGY,
} from './inputsArrays';
import {
  InvestmentGroup,
  InvestmentType,
  ProjectInput,
  ProjectInputGroup,
  ProjectListingMarketType,
  ProjectListingType,
} from './listingConfig';

/**
 * Mapping of all project paths with it's step names as keys and inputs arrays
 * This should corresponds with the on in the webapp-admin repo and
 * should be used as source of truth for all inputs in the projects
 */

export const PROJECTS_MAPPING = {
  [InvestmentGroup.COLLECTIVE_INVESTMENT]: {
    [InvestmentType.FUND]: {
      [ProjectListingType.HEDGE_FUND]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: FUND_FUND_PM_GENERAL_INFO,
          fundStrategy: FUND_FUND_PM_STRATEGY,
          keyPerformanceIndicators: FUND_FUND_PM_KPI,
          investmentInfo: FUND_FUND_PM_INVESTMENT_INFO,
          documents: FUND_FUND_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: FUND_FUND_PM_GENERAL_INFO,
          fundStrategy: FUND_FUND_SM_STRATEGY,
          keyPerformanceIndicators: FUND_FUND_PM_KPI,
          investmentInfo: FUND_FUND_PM_INVESTMENT_INFO,
          documents: FUND_FUND_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.DEDICATED_FUND]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: FUND_FUND_PM_GENERAL_INFO,
          fundStrategy: FUND_FUND_PM_STRATEGY,
          keyPerformanceIndicators: FUND_FUND_PM_KPI,
          investmentInfo: FUND_FUND_PM_INVESTMENT_INFO,
          documents: FUND_FUND_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: FUND_FUND_PM_GENERAL_INFO,
          fundStrategy: FUND_FUND_SM_STRATEGY,
          keyPerformanceIndicators: FUND_FUND_PM_KPI,
          investmentInfo: FUND_FUND_PM_INVESTMENT_INFO,
          documents: FUND_FUND_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      /**
       * @type {string}
       * @deprecated Should be removed in followup releases
       */
      [ProjectListingType.FUND]: {
        [ProjectListingMarketType.PRIMARY]: {
          generalInfo: FUND_FUND_PM_GENERAL_INFO,
          fundStrategy: FUND_FUND_PM_STRATEGY,
          keyPerformanceIndicators: FUND_FUND_PM_KPI,
          investmentInfo: FUND_FUND_PM_INVESTMENT_INFO,
          documents: FUND_FUND_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          generalInfo: FUND_FUND_PM_GENERAL_INFO,
          fundStrategy: FUND_FUND_SM_STRATEGY,
          keyPerformanceIndicators: FUND_FUND_PM_KPI,
          investmentInfo: FUND_FUND_PM_INVESTMENT_INFO,
          documents: FUND_FUND_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
    },
  },
  [InvestmentGroup.DIRECT_INVESTMENT]: {
    [InvestmentType.DEBT]: {
      [ProjectListingType.REAL_ESTATE]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_RE_PM_GENERAL_INFO,
          assetInfo: DEBT_RE_PM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_RE_PM_KPI,
          investmentInfo: DEBT_RE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          nonFinancialInfo: DEBT_RE_PM_NONFINANCIAL_INFO,
          documents: DEBT_RE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_RE_SM_GENERAL_INFO,
          assetInfo: DEBT_RE_SM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_RE_PM_KPI,
          investmentInfo: DEBT_RE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          nonFinancialInfo: DEBT_RE_PM_NONFINANCIAL_INFO,
          documents: DEBT_RE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.PRIVATE_EQUITY]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_RE_PM_GENERAL_INFO,
          businessInfo: DEBT_PE_PM_BUSINESS_INFO,
          keyPerformanceIndicators: DEBT_PE_PM_KPI,
          investmentInfo: DEBT_PE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_PE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_RE_SM_GENERAL_INFO,
          businessInfo: DEBT_PE_SM_BUSINESS_INFO,
          keyPerformanceIndicators: DEBT_PE_SM_KPI,
          investmentInfo: DEBT_PE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_PE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.ART]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_ART_PM_GENERAL_INFO,
          assetInfo: DEBT_ART_PM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_ART_PM_KPI,
          investmentInfo: DEBT_ART_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_ART_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_ART_SM_GENERAL_INFO,
          assetInfo: DEBT_ART_SM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_ART_PM_KPI,
          investmentInfo: DEBT_ART_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_ART_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.INFRASTRUCTURE]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_INFRASTRUCTURE_PM_GENERAL_INFO,
          assetInfo: DEBT_INFRASTRUCTURE_PM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_INFRASTRUCTURE_PM_KPI,
          investmentInfo: DEBT_INFRASTRUCTURE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_INFRASTRUCTURE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_INFRASTRUCTURE_SM_GENERAL_INFO,
          assetInfo: DEBT_INFRASTRUCTURE_SM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_INFRASTRUCTURE_SM_KPI,
          investmentInfo: DEBT_INFRASTRUCTURE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_INFRASTRUCTURE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.COMMODITIES]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_INFRASTRUCTURE_PM_GENERAL_INFO,
          assetInfo: DEBT_INFRASTRUCTURE_PM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_INFRASTRUCTURE_PM_KPI,
          investmentInfo: DEBT_INFRASTRUCTURE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_INFRASTRUCTURE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: DEBT_INFRASTRUCTURE_SM_GENERAL_INFO,
          assetInfo: DEBT_INFRASTRUCTURE_SM_ASSET_INFO,
          keyPerformanceIndicators: DEBT_INFRASTRUCTURE_SM_KPI,
          investmentInfo: DEBT_INFRASTRUCTURE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: DEBT_INFRASTRUCTURE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
    },
    [InvestmentType.EQUITY]: {
      [ProjectListingType.REAL_ESTATE]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_RE_PM_GENERAL_INFO,
          assetInfo: EQUITY_RE_PM_ASSET_INFO,
          keyPerformanceIndicators: EQUITY_RE_PM_KPI_INFO,
          investmentInfo: EQUITY_RE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          nonFinancialInfo: EQUITY_RE_PM_NONFINANCIAL_INFO,
          documents: EQUITY_RE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_RE_SM_GENERAL_INFO,
          assetInfo: EQUITY_RE_SM_ASSET_INFO,
          keyPerformanceIndicators: EQUITY_RE_SM_KPI_INFO,
          investmentInfo: EQUITY_RE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          nonFinancialInfo: EQUITY_RE_SM_NONFINANCIAL_INFO,
          documents: EQUITY_RE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.PRIVATE_EQUITY]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_PE_PM_GENERAL_INFO,
          businessInfo: EQUITY_PE_PM_BUSINESS_INFO,
          keyPerformanceIndicators: EQUITY_PE_PM_KPI,
          investmentInfo: EQUITY_PE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: EQUITY_PE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_PE_SM_GENERAL_INFO,
          businessInfo: EQUITY_PE_SM_BUSINESS_INFO,
          keyPerformanceIndicators: EQUITY_PE_SM_KPI_INFO,
          investmentInfo: EQUITY_PE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: EQUITY_PE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.INFRASTRUCTURE]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_INFRASTRUCTURE_PM_GENERAL_INFO,
          assetInfo: EQUITY_INFRASTRUCTURE_PM_ASSET_INFO,
          keyPerformanceIndicators: EQUITY_INFRASTRUCTURE_PM_KPI,
          investmentInfo: EQUITY_INFRASTRUCTURE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: EQUITY_INFRASTRUCTURE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_INFRASTRUCTURE_SM_GENERAL_INFO,
          assetInfo: EQUITY_INFRASTRUCTURE_SM_ASSET_INFO,
          keyPerformanceIndicators: EQUITY_INFRASTRUCTURE_SM_KPI,
          investmentInfo: EQUITY_INFRASTRUCTURE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: EQUITY_INFRASTRUCTURE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
      [ProjectListingType.COMMODITIES]: {
        [ProjectListingMarketType.PRIMARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_INFRASTRUCTURE_PM_GENERAL_INFO,
          assetInfo: EQUITY_INFRASTRUCTURE_PM_ASSET_INFO,
          keyPerformanceIndicators: EQUITY_INFRASTRUCTURE_PM_KPI,
          investmentInfo: EQUITY_INFRASTRUCTURE_PM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: EQUITY_INFRASTRUCTURE_PM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
        [ProjectListingMarketType.SECONDARY]: {
          core: [],
          campaign: CAMPAIGN_INPUTS,
          generalInfo: EQUITY_INFRASTRUCTURE_SM_GENERAL_INFO,
          assetInfo: EQUITY_INFRASTRUCTURE_SM_ASSET_INFO,
          keyPerformanceIndicators: EQUITY_INFRASTRUCTURE_SM_KPI,
          investmentInfo: EQUITY_INFRASTRUCTURE_SM_INVESTMENT_INFO,
          guaranteeLevels: [],
          documents: EQUITY_INFRASTRUCTURE_SM_DOCUMENTS,
          contactInfo: CONTACT_INFO,
        },
      },
    },
  },
};

export type ProjectMappingReturn = Omit<
  {
    [key in ProjectInputGroup]: Array<ProjectInput>;
  },
  'campaign'
> & { campaign?: Array<ProjectInput> };
